### ISSUE TITLE
Lossless codec support

### ISSUE THREAD

**Issue by brian6932** [Bnyro/RecordYou#86]
### Describe your suggested feature

I saw #17 so I edited this issue, FLAC would be ideal, but since it's not currently possible, maybe WAV or ALAC.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can find the list of supported audio formats and containers here: https://github.com/Bnyro/RecordYou/issues/20#issuecomment-1443566578. I'm not really familiar with all of them so if there is one that's lossless that'd be ideal, otherwise we might need to find an other solution by using a different way to record the files.
So I'm depending on your knowledge about these formats and codes ;)

**Comment by brian6932** [comment]
There doesn't seem to be any lossless codecs from that list 🤔
